name: Run tests

on: [push]

jobs:

  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebug

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Assemble app debug APK
        run: ./gradlew assembleDebug

      - name: Upload app APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble app instrumentation tests
        run: ./gradlew assembleDebugAndroidTest

      - name: Upload app test APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: UI Tests
    needs: apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Download app test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - id: Auth
        name: Test Lab authentication
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          credentials_json: ${{ secrets.TEST_LAB_AUTH }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Use gcloud CLI
        run: gcloud info

      - name: Run instrumentation tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=cheetah,version=33
